#import <AppKit/AppKit.h>
#include <stdbool.h>

@interface JVPasteboardProvider : NSObject <NSPasteboardItemDataProvider>
@property (nonatomic, copy) NSString *text;
@property (nonatomic, assign) BOOL wasRequested;
@end

@implementation JVPasteboardProvider
- (void)pasteboard:(NSPasteboard *)pasteboard item:(NSPasteboardItem *)item provideDataForType:(NSPasteboardType)type {
    self.wasRequested = YES;
    if ([type isEqualToString:NSPasteboardTypeString]) {
        [item setString:self.text forType:NSPasteboardTypeString];
    } else {
        [item setData:[NSData data] forType:type];
    }
}
@end

static JVPasteboardProvider *g_current_provider = nil;

bool jv_write_temporary_with_provider(const char *pb_name, const char *utf8_text) {
    if (!utf8_text) return false;
    @autoreleasepool {
        NSString *str = [NSString stringWithUTF8String:utf8_text];
        if (!str) return false;

        NSPasteboard *pb = nil;
        if (pb_name && strlen(pb_name) > 0) {
            NSString *nameStr = [NSString stringWithUTF8String:pb_name];
            pb = [NSPasteboard pasteboardWithName:nameStr];
        }
        if (!pb) {
            pb = [NSPasteboard generalPasteboard];
        }
        [pb clearContents];

        g_current_provider = [[JVPasteboardProvider alloc] init];
        g_current_provider.text = str;
        g_current_provider.wasRequested = NO;

        NSPasteboardItem *item = [[NSPasteboardItem alloc] init];
        NSArray *types = @[
            NSPasteboardTypeString,
            @"org.nspasteboard.TransientType",
            @"org.nspasteboard.AutoGeneratedType",
            @"org.nspasteboard.ConcealedType"
        ];
        [item setDataProvider:g_current_provider forTypes:types];

        return [pb writeObjects:@[item]];
    }
}

bool jv_did_target_paste(double timeout_seconds) {
    NSDate *deadline = [NSDate dateWithTimeIntervalSinceNow:timeout_seconds];
    while ([[NSDate date] compare:deadline] == NSOrderedAscending) {
        if (g_current_provider && g_current_provider.wasRequested) {
            return true;
        }
        [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:0.02]];
    }
    return g_current_provider ? g_current_provider.wasRequested : false;
}

void jv_clear_provider(void) {
    g_current_provider = nil;
}
